In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.losses import binary_crossentropy, categorical_crossentropy
from tensorflow_addons.losses import sigmoid_focal_crossentropy

In [2]:
y_pred = tf.Variable([
    [0.6, 0.2, 0.2],
    [0.2, 0.6, 0.2],
    [0.2, 0.2, 0.6],
])
y_true = tf.Variable([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1],
])

In [4]:
binary_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.3190374, 0.3190374, 0.3190374], dtype=float32)>

In [15]:
sigmoid_focal_crossentropy(y_true, y_pred, alpha=1.0, gamma=1.0)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.20433015, 0.20433015], dtype=float32)>

In [13]:
y_pred = tf.Variable([
    [0.6, 0.4],
    [0.4, 0.6],
])
y_true = tf.Variable([
    [1, 0],
    [0, 1],
])

In [14]:
binary_crossentropy(y_true, y_pred)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.5108254, 0.5108254], dtype=float32)>

In [2]:
x = tf.random.uniform((32, 128, 128, 4))

degrees = 2
layer = BCHConv2D(
    1,
    3,
    degrees=degrees,
    initializer=tf.keras.initializers.Constant(value=1),
    radial_profiles_sigma=0.25,
)
y = layer(x)


In [3]:
atoms = np.squeeze(layer.conv_ch.atoms.numpy())

In [4]:
atoms.shape

(3, 3, 5, 2)

In [5]:
np.abs(atoms[:,:,0,0]) 

array([[0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.]], dtype=float32)

In [6]:
np.abs(atoms[:, :, 0, 1])


array([[0.58578646, 1.        , 0.58578646],
       [1.        , 0.        , 1.        ],
       [0.58578646, 1.        , 0.58578646]], dtype=float32)